"""added votes column to posts

Revision ID: 09f4e478ad20
Revises: c3225b809cee
Create Date: 2019-01-25 14:49:21.573695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09f4e478ad20'
down_revision = 'c3225b809cee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('downvotes', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('upvotes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'upvotes')
    op.drop_column('post', 'downvotes')
    # ### end Alembic commands ###
