"""added comments topics to post

Revision ID: 7f94b6351dc7
Revises: 4f038204af64
Create Date: 2019-01-28 10:03:25.692720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f94b6351dc7'
down_revision = '4f038204af64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('topic', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'topic', ['topic'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'topic')
    # ### end Alembic commands ###
